import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Sidebar} from "@/src/components/layout/sidebar/SideBar";
import {cookies} from "next/headers";
import {UserStoreInitializer} from "@/src/components/providers/UserStoreInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies()
  const userId = cookieStore.get('userId')?.value
  const userName = cookieStore.get('userName')?.value
  const userEmail = cookieStore.get('userEmail')?.value
  const userRole = cookieStore.get('userRole')?.value as 'FREE' | 'PRO' | 'ADMIN' | undefined
  return (
      <html
          lang="en"
          className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body>
        {userId && userRole && userName && userEmail && (
            <UserStoreInitializer
                userId={userId}
                userName={userName}
                userEmail={userEmail}
                userRole={userRole}
            />
        )}
        <Sidebar />
        {children}
        </body>
      </html>
  );
}
